badges = {
  "Blinding Light of Destiny": 6,
  "Sepulchure's Armor": 7,
  "Necrotic Sword of Doom": 10,
  "Drakath's Epic Armor": 6,
  "Blade of Awe": 2,
  "Legion Revenant": 9,
  "Void Highlord": 9,
  "Celestial Pirate Commander": 3,
  "Dragon of Time": 8,
  "Awe Ascension": 9,
  "Head of the Legion Beast": 7,
  "Apotheosis": 8,
  "Chaos Avenger": 7,
  "Hollowborn Paladin": 6,
  "Hollowborn DoomKnight": 7
}

classes = {
  "Dark Lord": 2,
  "Scarlet Sorceress": 2,
  "Shadow Dragon Shinobi": 2,
  "Vampire Lord": 2,
  "ArchPaladin": 3,
  "Chrono Assassin": 3,
  "Cryomancer": 3,
  "DragonSoul Shinobi": 3,
  "Evolved Leprechaun": 3,
  "Frostval Barbarian": 3,
  "ShadowScythe General": 3,
  "The Collector": 3,
  "Frost SpiritReaver": 4,
  "Blaze Binder": 5,
  "StoneCrusher": 5,
  "Lord Of Order": 6,
  "ArchFiend": 7,
  "Yami no Ronin": 7
}

easy = {
  "Akriloth Pet": 1,
  "Blood of the Void Blade": 1,
  "Blood of the Void Daggers": 1,
  "Purified Void Blade": 1,
  "Purified Void Daggers": 1,
  "Apa's Outfit": 1,
  "Eta's Outfit": 1,
  "Eternity Blade": 1,
  "Incarnation of Glitches Scythe": 1,
  "Skull Pauldrons of Vordred": 1,
  "Treasured Hero of Gold": 1,
  "Altar of Caladbacon": 2,
  "Burning Blade Of Abezeth": 2,
  "Chaos PuppetMaster": 2,
  "DOOMFire OF Gravelyn": 2,
  "Drago's Cloaked Attire": 2,
  "Ecto Enforcer": 2,
  "Flaming Soulfire Warmonger": 2,
  "Hel Fö In Officio": 2,
  "Hollowborn Judge In Officio": 2,
  "Iara's Acolyte": 2,
  "Kala's Living Head": 2,
  "Reho's Golden Sword": 2,
  "Sapphire SpellBlade": 2,
  "Void Monk of Nulgath": 2,
  "Void Paladin": 2,
  "Void Sorcerer": 2,
  "Zorbak Dracolich Rider": 2,
  "ArchFiend Spear": 3,
  "Dalang Sinden": 3,
  "Fiend of Light": 3,
  "Sheer Insanity": 3,
  "Taro's Prismatic Manslayer": 3,
  "Ultimate Lich King": 3,
  "Void Avenger Scythe": 3
}

medium = {
  "Arch DoomKnight": 4,
  "Archfiend DeathLord": 4,
  "Dawn Vindicator Inquisitor": 4,
  "Drakath the Eternal": 4,
  "Fallen DeathKnight": 4,
  "Hollowborn Oblivion Blade": 4,
  "Infernal Flame Khopesh": 4,
  "Legion Spellcaster": 4,
  "ShadowCharged Empress Blade": 4,
  "ShadowFlame DoomLight": 4,
  "Vordred's Armor": 4,
  "Yulgath's Inn": 4,
  "Darkon's Debris 66.3": 5,
  "Darkon's Debris 92.3": 5,
  "Dual Blinding Caladbolgs": 5,
  "Enchanted FireDrake's Lance": 5,
  "Enchanted ShadowDrake's Lance": 5,
  "Exalted Duality": 5,
  "Infernal Flame Pyromancer": 5,
  "Laken the Seraphic Paladin": 5,
  "Mutated Pink Trobbolier Morph": 5,
  "Polished Blinding Light of Destiny": 5,
  "Reborn Sepulchure's Helm": 5,
  "Shadow Dragon Defender": 5,
  "Void Light of Destiny": 5,
  "GrimDark": 6,
  "Legion Castle": 6,
  "Void Shogun": 6,
  "Void Spartan": 6,
  "Void Warlock": 6
}

hard = {
  "ArchFiend DoomLord": 7,
  "Archfiend Warlord": 7,
  "Armor of Awe": 7,
  "Enchanted Nulgath Nation House": 7,
  "Fire Champion's Armor": 7,
  "Hollowborn Reaper's Scythe": 7,
  "Necrotic Blade of the Underworld": 7,
  "Prince Darkon's Poleaxe": 7,
  "Empowered Bonfire Altar": 8,
  "Empowered Forge Spawn": 8,
  "Empowered Lich King": 8,
  "Legion Bonfire Altar": 8,
  "Legion Forge Spawn": 8
}

points = {
  "Blinding Light of Destiny": 6,
  "Sepulchure's Armor": 7,
  "Necrotic Sword of Doom": 10,
  "Drakath's Epic Armor": 6,
  "Blade of Awe": 2,
  "Legion Revenant": 9,
  "Void Highlord": 9,
  "Celestial Pirate Commander": 3,
  "Dragon of Time": 8,
  "Awe Ascension": 9,
  "Head of the Legion Beast": 7,
  "Apotheosis": 8,
  "Chaos Avenger": 7,
  "Hollowborn Paladin": 6,
  "Hollowborn DoomKnight": 7,
  "Dark Lord": 2,
  "Scarlet Sorceress": 2,
  "Shadow Dragon Shinobi": 2,
  "Vampire Lord": 2,
  "ArchPaladin": 3,
  "Chrono Assassin": 3,
  "Cryomancer": 3,
  "DragonSoul Shinobi": 3,
  "Evolved Leprechaun": 3,
  "Frostval Barbarian": 3,
  "ShadowScythe General": 3,
  "The Collector": 3,
  "Frost SpiritReaver": 4,
  "Blaze Binder": 5,
  "StoneCrusher": 5,
  "Lord Of Order": 6,
  "ArchFiend": 7,
  "Yami no Ronin": 7,
  "Akriloth Pet": 1,
  "Blood of the Void Blade": 1,
  "Blood of the Void Daggers": 1,
  "Purified Void Blade": 1,
  "Purified Void Daggers": 1,
  "Apa's Outfit": 1,
  "Eta's Outfit": 1,
  "Eternity Blade": 1,
  "Incarnation of Glitches Scythe": 1,
  "Skull Pauldrons of Vordred": 1,
  "Treasured Hero of Gold": 1,
  "Altar of Caladbacon": 2,
  "Burning Blade Of Abezeth": 2,
  "Chaos PuppetMaster": 2,
  "DOOMFire OF Gravelyn": 2,
  "Drago's Cloaked Attire": 2,
  "Ecto Enforcer": 2,
  "Flaming Soulfire Warmonger": 2,
  "Hel Fö In Officio": 2,
  "Hollowborn Judge In Officio": 2,
  "Iara's Acolyte": 2,
  "Kala's Living Head": 2,
  "Reho's Golden Sword": 2,
  "Sapphire SpellBlade": 2,
  "Void Monk of Nulgath": 2,
  "Void Paladin": 2,
  "Void Sorcerer": 2,
  "Zorbak Dracolich Rider": 2,
  "ArchFiend Spear": 3,
  "Dalang Sinden": 3,
  "Fiend of Light": 3,
  "Sheer Insanity": 3,
  "Taro's Prismatic Manslayer": 3,
  "Ultimate Lich King": 3,
  "Void Avenger Scythe": 3,
  "Arch DoomKnight": 4,
  "Archfiend DeathLord": 4,
  "Dawn Vindicator Inquisitor": 4,
  "Drakath the Eternal": 4,
  "Fallen DeathKnight": 4,
  "Hollowborn Oblivion Blade": 4,
  "Infernal Flame Khopesh": 4,
  "Legion Spellcaster": 4,
  "ShadowCharged Empress Blade": 4,
  "ShadowFlame DoomLight": 4,
  "Vordred's Armor": 4,
  "Yulgath's Inn": 4,
  "Darkon's Debris 66.3": 5,
  "Darkon's Debris 92.3": 5,
  "Dual Blinding Caladbolgs": 5,
  "Enchanted FireDrake's Lance": 5,
  "Enchanted ShadowDrake's Lance": 5,
  "Exalted Duality": 5,
  "Infernal Flame Pyromancer": 5,
  "Laken the Seraphic Paladin": 5,
  "Mutated Pink Trobbolier Morph": 5,
  "Polished Blinding Light of Destiny": 5,
  "Reborn Sepulchure's Helm": 5,
  "Shadow Dragon Defender": 5,
  "Void Light of Destiny": 5,
  "GrimDark": 6,
  "Legion Castle": 6,
  "Void Shogun": 6,
  "Void Spartan": 6,
  "Void Warlock": 6,
  "ArchFiend DoomLord": 7,
  "Archfiend Warlord": 7,
  "Armor of Awe": 7,
  "Enchanted Nulgath Nation House": 7,
  "Fire Champion's Armor": 7,
  "Hollowborn Reaper's Scythe": 7,
  "Necrotic Blade of the Underworld": 7,
  "Prince Darkon's Poleaxe": 7,
  "Empowered Bonfire Altar": 8,
  "Empowered Forge Spawn": 8,
  "Empowered Lich King": 8,
  "Legion Bonfire Altar": 8,
  "Legion Forge Spawn": 8
}
